# Generated by Django 6.1.1 on 2026-10-06 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("method", models.CharField(max_length=16)),
                ("path", models.CharField(max_length=2048)),
                (
                    "principal",
                    models.CharField(
                        blank=True,
                        help_text="The user's pk, or blank when signed out.",
                        max_length=64,
                    ),
                ),
                (
                    "body_hash",
                    models.CharField(help_text="sha256 of the raw request body.", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("reserved", "Reserved"), ("completed", "Completed")],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.BinaryField(default=b"")),
                ("response_content_type", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
