"""Tests for apps.pwa.views: manifest, service worker and offline page."""

import json

import pytest
from django.test import Client
from django.test.utils import override_settings
from django.urls import reverse

from apps.pwa import conf
from apps.pwa.views import worker_config


def test_manifest_is_installable(client: Client) -> None:
    """The manifest has what browsers need to offer installation."""
    response = client.get(reverse("pwa:manifest"))
    assert response["Content-Type"] == "application/manifest+json"
    data = json.loads(response.content)
    assert data["name"] == conf.APP_NAME
    assert data["display"] == "standalone"
    assert data["start_url"] == reverse("activity:app") == conf.SCOPE
    assert data["scope"] == data["id"] == conf.SCOPE
    sizes = {icon["sizes"] for icon in data["icons"]}
    assert {"192x192", "512x512"} <= sizes
    assert any(icon.get("purpose") == "maskable" for icon in data["icons"])


def test_service_worker_lives_in_the_app_scope(client: Client) -> None:
    """The worker is served from inside /app/, so it controls the app and nothing else."""
    url = reverse("pwa:service_worker")
    assert url.startswith(conf.SCOPE)
    response = client.get(url)
    assert response["Content-Type"] == "text/javascript"
    assert response["Cache-Control"] == "no-cache"
    assert "Service-Worker-Allowed" not in response
    body = response.content.decode()
    assert body.startswith("// Generated by")
    assert "importScripts(" in body


def test_service_worker_precaches_the_shell() -> None:
    """The offline page and every precached file are in the worker's config."""
    config = worker_config()
    assert config["offlineUrl"] == reverse("pwa:offline")
    assert len(config["precache"]) == len(conf.PRECACHE_STATIC)  # type: ignore[arg-type]
    assert config["scope"] == conf.SCOPE
    assert config["workerUrl"] == reverse("pwa:service_worker")


def test_worker_version_changes_with_the_deploy() -> None:
    """A new commit means new cache names, so devices drop stale files."""
    with override_settings(APP_VERSION="aaa"):
        first = worker_config()["version"]
    with override_settings(APP_VERSION="bbb"):
        second = worker_config()["version"]
    assert first != second


@override_settings(DEBUG=True)
def test_worker_version_tracks_file_contents_in_debug() -> None:
    """In DEBUG the version hashes the files themselves, so edits roll the caches."""
    assert worker_config()["debug"] is True
    assert len(str(worker_config()["version"])) == 12


@pytest.mark.django_db
def test_offline_page_is_public(client: Client) -> None:
    """The worker fetches the offline page at install, possibly signed out."""
    response = client.get(reverse("pwa:offline"))
    assert response.status_code == 200
    assert b"You're offline" in response.content


def test_context_processor_exposes_the_app_identity(rf: object) -> None:
    """Templates get the name and colours as ``pwa``."""
    from apps.pwa.context_processors import pwa

    context = pwa(rf.get("/"))  # type: ignore[attr-defined]
    assert context["pwa"]["name"] == conf.APP_NAME
    assert context["pwa"]["theme_colour"] == conf.THEME_COLOUR
    assert context["pwa"]["scope"] == conf.SCOPE
