"""Views for the PWA shell.

The service worker is built here rather than served as a static file for
two reasons: it must live at ``/app/sw.js`` to control ``/app/`` (a worker
controls only paths under its own), and it needs the hashed URLs of the
files it precaches, which only exist after ``collectstatic``. The logic
itself is plain static JavaScript (``static/js/sw_*.js``); this view writes
a few lines of config and imports it.
"""

import hashlib
import json

from django.conf import settings
from django.contrib.staticfiles import finders
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.templatetags.static import static
from django.urls import reverse
from django.views.decorators.cache import cache_control
from django.views.decorators.http import require_GET

from apps.pwa import conf


@require_GET
@cache_control(max_age=3600)
def manifest(request: HttpRequest) -> HttpResponse:
    """Return the web app manifest."""
    data = {
        "id": conf.SCOPE,
        "name": conf.APP_NAME,
        "short_name": conf.SHORT_NAME,
        "description": conf.DESCRIPTION,
        "start_url": reverse("activity:app"),
        "scope": conf.SCOPE,
        "display": "standalone",
        "theme_color": conf.THEME_COLOUR,
        "background_color": conf.BACKGROUND_COLOUR,
        "icons": [
            {"src": static("icons/icon-192.png"), "sizes": "192x192", "type": "image/png"},
            {"src": static("icons/icon-512.png"), "sizes": "512x512", "type": "image/png"},
            {
                "src": static("icons/icon-maskable-512.png"),
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "maskable",
            },
        ],
    }
    return JsonResponse(data, content_type="application/manifest+json")


def worker_config() -> dict[str, object]:
    """Return the config the service worker runs with, including its version.

    The version is a hash of everything the worker would cache, so a deploy
    that changes any precached file (its hashed URL changes) gets new caches.
    In DEBUG the URLs are not hashed, so the files' contents go into the
    hash instead and an edit still rolls the caches during development.
    """
    config: dict[str, object] = {
        "prefix": conf.CACHE_PREFIX,
        "debug": settings.DEBUG,
        "staticUrl": settings.STATIC_URL
        if settings.STATIC_URL.startswith("/")
        else f"/{settings.STATIC_URL}",
        "scope": conf.SCOPE,
        "workerUrl": reverse("pwa:service_worker"),
        "offlineUrl": reverse("pwa:offline"),
        "neverCache": conf.NEVER_CACHE,
        "precache": [static(p) for p in conf.PRECACHE_STATIC],
        "scripts": [static(p) for p in conf.WORKER_SCRIPTS],
    }
    digest = hashlib.sha256(json.dumps(config, sort_keys=True).encode())
    digest.update(settings.APP_VERSION.encode())
    if settings.DEBUG:
        for path in sorted(set(conf.PRECACHE_STATIC + conf.WORKER_SCRIPTS)):
            if found := finders.find(path):
                with open(str(found), "rb") as f:
                    digest.update(f.read())
    config["version"] = digest.hexdigest()[:12]
    return config


@require_GET
def service_worker(request: HttpRequest) -> HttpResponse:
    """Return /app/sw.js: the worker's config, then importScripts() of its logic."""
    config = worker_config()
    scripts = ", ".join(json.dumps(static(p)) for p in conf.WORKER_SCRIPTS)
    body = (
        "// Generated by apps.pwa.views.service_worker. The logic is in static/js/sw_*.js.\n"
        f"self.SW_CONFIG = {json.dumps(config, sort_keys=True)};\n"
        f"importScripts({scripts});\n"
    )
    response = HttpResponse(body, content_type="text/javascript")
    # Browsers re-check the worker on every navigation; never let an HTTP
    # cache answer for it, or a deploy can take a day to reach a device.
    response["Cache-Control"] = "no-cache"
    return response


@require_GET
def offline(request: HttpRequest) -> HttpResponse:
    """The page the worker shows for a page it has never cached, while offline.

    Public and user-free, because the worker fetches it at install time.
    """
    return render(request, "pwa/offline.html")
